site_name: TW GPSS (Unofficial) MCP Tools Documentation
site_author: Hsiang-Jen Li
theme:
  name: readthedocs
plugins:
  - search
  - neoteroi.mkdocsoad
nav:
  - Home: index.md
  - API Reference:
    - Swagger: reference/endpoints_swagger.md